### ISSUE TITLE
Feature Request : noindex,follow tag on unwanted q2a pages

### ISSUE THREAD

**Issue by Dr-Hack** [q2a-projects/Q2A-Ultimate-SEO#11]
reference : http://www.question2answer.org/qa/42526/is-there-a-plugin-to-noindex-specific-questions?show=42526#q42526

any plans of adding an option , where we an add <meta name="robots" content="noindex,follow"> to all the unwanted pages ? as it turns out google wont show the question but will list site/questions which is really annoying and puts a drop in result ranking

thanks

**Comment by Towhidn** [comment]
It's a good idea. but won't have free time to review and add features to this plugin any time soon.
