### ISSUE TITLE
"Parameter must be an array or an object" warning message at the top of the site (q2a 1.8.0)

### ISSUE THREAD

**Issue by mugenishere** [q2a-projects/Q2A-Ultimate-SEO#13]
This is the complete error: 

> Warning: count(): Parameter must be an array or an object that implements Countable in (my site's address)\qa-include\qa-base.php(725) : eval()'d code on line 160

I am using version 1.8.0. I've currently removed it from my site until this gets fixed. I request you to please look into this matter at the earliest. IF you need any further information from me then please let me know.

**Comment by tanmuhittin** [comment]
the same here!

**Comment by leashadav** [comment]
just installed this and getting same error, can someone please help to fix this? Thank you.

**Comment by KenyayoteDevelopers** [comment]
There is fix to the error in this page: [How to fix Q2A-Ultimate-SEO Count() error in line 160](https://blogiestools.com/how-to-fix-q2a-ultimate-seo-count-error-in-line-160/)
