### ISSUE TITLE
update 

### ISSUE THREAD

**Issue by zerg052689** [q2a-projects/Q2A-Ultimate-SEO#18]
update this please, i have an error for latest version QA. 

Warning: count(): Parameter must be an array or an object that implements Countable in  /qa-base.php(626) : eval()'d code on line 160

**Comment by java-boy** [comment]
This plugin needs update 
Please update it @TohidN 
Best wishes brother

**Comment by java-boy** [comment]
Also, it is good to mention that this gentleman has forked and updated this plugin:
[https://github.com/pupi1985/q2a-pupi-srs](https://github.com/pupi1985/q2a-pupi-srs)
