### ISSUE TITLE
500 internal server error 

### ISSUE THREAD

**Issue by osk386** [q2a-projects/Q2A-Ultimate-SEO#5]
Hi, I've just installed your interesting plugin, but when I click on the Admin > Ultimate SEO link, it takes me to 500 internal server error page. The curious case is that after installation of this plugin, the Admin > hidden page takes me to 500 error page too, but when I uninstall this plugin, hidden page works again.

this is my .htaccess file 

DirectoryIndex index.php
<IfModule mod_rewrite.c>
RewriteEngine On
# RewriteBase /

RewriteCond %{REQUEST_URI} ^(._)//(._)$
RewriteRule . %1/%2 [R=301,L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^.*$ index.php?qa-rewrite=$0&%{QUERY_STRING} [L]
</IfModule>

The link generated to enter to Ultimate SEO page is : 

http://www.mysite.com/index.php?qa=admin&qa_1=ulitmate_seo 

I appreciate your help

**Comment by Towhidn** [comment]
This might be a compatibility problem with Q2A 1.7. I'm planning to make a full compatibility check in next few days and release new version.

If you are not using Q2A 1.7 then please check your Log-File for this error and send it here. also it might help if you could send me name of the theme & plugins that you use.

If I couldn't catch the error, then I can test it on your site to fix it.

**Comment by osk386** [comment]
Well, I just realized that it occurs on every question page too, but only in a goDaddy domain, I tried the same configuration with same data in a local environment, and all works perfectly with the ultimate seo plugin.

So the problem resides on godaddy, caused by some uncompatibilities with the plugin.

:(

**Comment by Towhidn** [comment]
so I can't generate and this error in my development environment, however I'm willing to track this issue in your server and add a fix to plugin to resolve all it's issues. if you agree, please send me your server's hosting detail in contact form on my site.
