### ISSUE TITLE
Feature Request: Add Meta site description and Meta Tags 

### ISSUE THREAD

**Issue by gurjyot** [q2a-projects/Q2A-Ultimate-SEO#6]
This plugin is a complete seo plugin for Q2A, then why not to add this one more feature in this plugin. Because adding Meta Site description and Meta Tags also help in better recognition of website in Google. So this feature will also help a lot of people in terms of seo.

**Comment by Towhidn** [comment]
Using this plugin Meta tags(title & description) can be edited in questions. 

note that Q2A automatically generates meta tags, however you can change default meta information to use Answer Content as meta description or edit both tags for each question.

to enable meta tag editor:
1. visit "Admin > Ultimate SEO > Meta Tags"  then enable editor.
2. visit a question and you will find Meta Editor in the page.

**Comment by gurjyot** [comment]
Hello @Towhidn, this is for meta description of questions. But what I am saying is about the meta description of the website. It shows when the site name is types in the Google search. And this meta site description of the main site is never changed so it would be good to have a field for this directly under the plugin.
