### ISSUE TITLE
This plugin is showing warning on just one question.

### ISSUE THREAD

**Issue by gurjyot** [q2a-projects/Q2A-Ultimate-SEO#7]
I have raised this question on Q2A Q&A. You can see the exact problem there.

http://question2answer.org/qa/46126

**Comment by gurjyot** [comment]
Hello towhid... The problem is fixed in the updates done by pupi1985 in his fork... 
https://github.com/pupi1985/Q2A-Ultimate-SEO

**Comment by gurjyot** [comment]
Any update for this problem..?

**Comment by Towhidn** [comment]
thanks for reminding me. I marked it and will apply changes in next
few days as soon as I get an hour if free time(since I must apply them
manually).
Cheers

**Comment by gurjyot** [comment]
Have you finally got sometime to fix this issue...?? Or do we have to wait some more...??

**Comment by gurjyot** [comment]
Any update to this...?

**Comment by Towhidn** [comment]
Fixes are applied. Thanks for reporting.

**Comment by Towhidn** [comment]
Fixes are applied. Thanks for reporting.
